
const arr = [
  {
    key: 1,
    image: "/main-gallery/frida-kahlo/portrait8.jpg",
    imgAlt: "Frida Kahlo wearing a thorn necklace",
    imgCrop: "/main-gallery/frida-kahlo/portrait8.jpg",
    title: "Self-Portrait with Thorn Necklace and Hummingbird",
    artist: "Frida Kahlo",
    artistDesc: "Mexican painter Frida Kahlo was a revolutionary famous for her works depicting her struggles with her body image and gender identity. She is particularly well known for her self-portraits with her iconic unibrow, braided hair and traditional clothing. She spent most of her time as an artist in the United States and Mexico and later became an outspoken participant in the Mexican revolution in the 1910’s and 20s.",
    artistPic: "/main-gallery/frida-kahlo/frida-kahlo.jpg",
    other: [
      {otitle: "Memory, the Heart", oimg: "/main-gallery/frida-kahlo/fk-memory.jpg", odate: "1937"},
      {otitle: "What the Water Gave Me", oimg: "/main-gallery/frida-kahlo/fk-water.jpg", odate: "1938"},
      {otitle: "Self-Portrait with Monkey", oimg: "/main-gallery/frida-kahlo/sp-monkey.jpg", odate: "1938"},
    ],
    date: "	1940",
    location: "Mexico",
    description: "This portrait was painted by Kahlo herself surrounded by symbols of indigenous Mexican culture, a powerful message during the time of the Mexican revolution. The hummingbird around her neck represents good luck for falling in love or alternatively Huitzilopochtli – the Aztec god of war. The panther represents bad luck and death while the monkey symbolises evil.",
    metlink: "https://www.britishmuseum.org/collection/object/EA_Am-B5-23"},
  {
    key: 2,
    image: "/main-gallery/portrait1.jpg",
    imgAlt: "Vang Gogh wearing a straw hat",
    imgCrop: "/main-gallery/portrait1-crop.jpg",
    title: "Self-Portrait with a Straw Hat",
    artist: "Vincent Van Gogh",
    artistDesc: "Vincent van Gogh was a Dutch painter who spent many of his working years in France. He revolutionised the impressionist art movement and went on to become one of the most prolific and well-known artists of the 20th century. Surprisingly while Van Gogh was alive many of his art works were not well received and they did not get the accolades they deserved until well after his death. Van Gogh painted a myriad of oil paintings of a variety of subjects including portraits, still life, and landscapes. Van Gogh suffered with severe depression exacerbated by his poor commercial and financial success. He committed suicide in July 1890.",
    artistPic: "/main-gallery/van-gogh/van-gogh.jpg",
    other: [
      {otitle: "Starry Night Over the Rhine", oimg: "/main-gallery/van-gogh/starry-night.jpg", odate: "1888"},
      {otitle: "Still Life: Vase with Fourteen Sunflowers", oimg: "/main-gallery/van-gogh/14-flowers.jpg", odate: "1888"},
      {otitle: "A Wheatfield with Cypresses", oimg: "/main-gallery/van-gogh/wheat-field.jpg", odate: "1889"},
    ],
    date: "1887",
    location: "France",
    description: "This self portrait was one 20 portraits Van Gogh painted during his stay in Paris. Painted in his signature impressionist style.",
    metlink: "https://www.metmuseum.org/art/collection/search/436532"},
  {
    key: 3,
    image: "/main-gallery/artemisia.jpg",
    imgAlt: "Artemisia painting on a canvas",
    imgCrop: "/main-gallery/portrait4-crop.jpg",
    title: "Self-portrait as the Allegory of Painting",
    artist: "Artemisia Gentileschi",
    artistDesc: "Artemisia Gentileschi was one of the most famous artists of her time and one of the few female artists to receive such widespread recognition. Born in Rome, 1593, Gentileschi became well known for her vivid artworks depicting biblical scenes and gathered a myriad of powerful patrons, including the House of Medici. Gentileschi became the first woman to become a member of the Accademia di Arte sel Disegno, a prestigious art academy founded by Cosimo I de’ Medici. She joined the ranks as one of its famous alumni alongside artist like Michelangelo and Giambologna.",
    artistPic: "/main-gallery/artemisia/artemisia-g.jpg",
    other: [
      {otitle: "Judith Slaying Holofernes", oimg: "/main-gallery/artemisia/judith-holofernes.jpg", odate: "1611 - 1612"},
      {otitle: "Esther Before Ahasuerus", oimg: "/main-gallery/artemisia/esther.jpg", odate: "1628 - 1635"},
      {otitle: "Samson and Delilah", oimg: "/main-gallery/artemisia/delilah.jpg", odate: "1630 - 1638"},
    ],
    date: "1638-1639",
    location: "Italy",
    description: "The allegory of painting was one of the few self portraits Gentileschi pained. She represented herself as the allegory of painting, challenging the male dominated profession at the time.",
    metlink: "https://www.rct.uk/collection/405551/self-portrait-as-the-allegory-of-painting-la-pittura"},
  {
    key: 4,
    image: "/main-gallery/portrait3.jpg",
    imgAlt: "A man with his hands in his hair and a terrified expression",
    imgCrop: "/main-gallery/portrait3-crop.jpg",
    title: "Le Désespéré",
    artist: "Gustave Courbet",
    artistDesc: "Gustave Courbet was a French painter born in France in 1817. Courbet depicted a variety of themes and srt styles in his works and they became a reflection of his political acticity. His political affiliations would later land him in prision and eventually exile in 1873. He remained in exile in Switzerland until his death in 1877.",
    artistPic: "/main-gallery/courbet/courbet.jpg",
    other: [
      {otitle: "Self Portrait with a Black Dog", oimg: "/main-gallery/courbet/black-dog.jpg", odate: "1842 - 1844"},
      {otitle: "The Calm Sea", oimg: "/main-gallery/courbet/sea.jpg", odate: "1869"},
      {otitle: "The Trellis", oimg: "/main-gallery/courbet/trellis.jpg", odate: "1862"},
    ],
    date: "1843-1845",
    location: "Paris,France",
    description: "Le Désespéré is a striking portrait painted by Gustave Courbet. Interestingly, this portrait remained unknown until after the artists death in 1877. The oil painting is said to represent his plight as a tortured artist as he drifts further from the optimistic and romantisized ideas of his youth",
    metlink: "https://www.metmuseum.org/exhibitions/listings/2008/gustave-courbet/photo-gallery"},
  // {
  //   key: 5,
  //   image: "/main-gallery/artemisia.jpg",
  //   imgAlt: "",
  //   imgCrop: "/main-gallery/portrait4-crop.jpg",
  //   title: "Self-portrait as the Allegory of Painting",
  //   artist: "Artemisia Gentileschi",
  //   artistDesc: "Artemisia Gentileschi was one of the most famous artists of her time and one of the few female artists to receive such widespread recognition. Born in Rome, 1593, Gentileschi became well known for her vivid artworks depicting biblical scenes and gathered a myriad of powerful patrons, including the House of Medici. Gentileschi became the first woman to become a member of the Accademia di Arte sel Disegno, a prestigious art academy founded by Cosimo I de’ Medici. She joined the ranks as one of its famous alumni alongside artist like Michelangelo and Giambologna.",
  //   artistPic: "/main-gallery/artemisia/artemisia-g.jpg",
  //   other: [
  //     {otitle: "Judith Slaying Holofernes", oimg: "/main-gallery/artemisia/judith-holofernes.jpg", odate: "1611 - 1612"},
  //     {otitle: "Esther Before Ahasuerus", oimg: "/main-gallery/artemisia/esther.jpg", odate: "1628 - 1635"},
  //     {otitle: "Samson and Delilah", oimg: "/main-gallery/artemisia/delilah.jpg", odate: "1630 - 1638"},
  //   ],
  //   date: "1638-1639",
  //   location: "Italy",
  //   description: "The allegory of painting was one of the few self portraits Gentileschi pained. She represented herself as the allegory of painting, challenging the male dominated profession at the time.",
  //   metlink: "https://www.rct.uk/collection/405551/self-portrait-as-the-allegory-of-painting-la-pittura"}
  // {
  //   key: 6,
  //   image: "/main-gallery/portrait5.jpg",
  //   imgAlt: "",
  //   imgCrop: "/main-gallery/portrait5.jpg",
  //   title: "Self-Portrait in a Flat Cap",
  //   artist: "Rembrandt",
  //   artistDesc: "Mexican painter Frida Kahlo was a revolutionary famous for her works depicting her struggles with her body image and gender identity. She is particularly well known for her self-portraits with her iconic unibrow, braided hair and traditional clothing. She spent most of her time as an artist in the United States and Mexico and later became an outspoken participant in the Mexican revolution in the 1910’s and 20s.",
  //   artistPic: "/main-gallery/frida-kahlo/frida-kahlo.jpg",
  //   other: [
  //     {otitle: "Memory, the Heart", oimg: "/main-gallery/frida-kahlo/fk-memory.jpg", odate: "1937"},
  //     {otitle: "What the Water Gave Me", oimg: "/main-gallery/frida-kahlo/fk-water.jpg", odate: "1938"},
  //     {otitle: "Self-Portrait with Monkey", oimg: "/main-gallery/frida-kahlo/sp-monkey.jpg", odate: "1938"},
  //   ],
  //   date: "1642",
  //   location: "",
  //   description: "",
  //   metlink: "https://www.rct.uk/collection/404120/self-portrait-in-a-flat-cap"},
  // {
  //   key: 7,
  //   image: "/main-gallery/portrait6.jpg",
  //   imgAlt: "",
  //   imgCrop: "/main-gallery/portrait6-crop.jpg",
  //   title: "A Young Woman in red",
  //   artist: "Unknown",
  //   artistDesc: "Mexican painter Frida Kahlo was a revolutionary famous for her works depicting her struggles with her body image and gender identity. She is particularly well known for her self-portraits with her iconic unibrow, braided hair and traditional clothing. She spent most of her time as an artist in the United States and Mexico and later became an outspoken participant in the Mexican revolution in the 1910’s and 20s.",
  //   artistPic: "/main-gallery/frida-kahlo/frida-kahlo.jpg",
  //   other: [
  //     {otitle: "Memory, the Heart", oimg: "/main-gallery/frida-kahlo/fk-memory.jpg", odate: "1937"},
  //     {otitle: "What the Water Gave Me", oimg: "/main-gallery/frida-kahlo/fk-water.jpg", odate: "1938"},
  //     {otitle: "Self-Portrait with Monkey", oimg: "/main-gallery/frida-kahlo/sp-monkey.jpg", odate: "1938"},
  //   ],
  //   date: "ca. A.D. 90–120",
  //   location: "Egypt",
  //   description: "",
  //   metlink: "https://www.metmuseum.org/art/collection/search/547860"},
  // {
  //   key: 8,
  //   image: "/main-gallery/portrait7.jpg",
  //   imgAlt: "",
  //   imgCrop: "/main-gallery/portrait7.jpg",
  //   title: "A Self-Portrait",
  //   artist: "Pan Yuliang",
  //   artistDesc: "Mexican painter Frida Kahlo was a revolutionary famous for her works depicting her struggles with her body image and gender identity. She is particularly well known for her self-portraits with her iconic unibrow, braided hair and traditional clothing. She spent most of her time as an artist in the United States and Mexico and later became an outspoken participant in the Mexican revolution in the 1910’s and 20s.",
  //   artistPic: "/main-gallery/frida-kahlo/frida-kahlo.jpg",
  //   other: [
  //     {otitle: "Memory, the Heart", oimg: "/main-gallery/frida-kahlo/fk-memory.jpg", odate: "1937"},
  //     {otitle: "What the Water Gave Me", oimg: "/main-gallery/frida-kahlo/fk-water.jpg", odate: "1938"},
  //     {otitle: "Self-Portrait with Monkey", oimg: "/main-gallery/frida-kahlo/sp-monkey.jpg", odate: "1938"},
  //   ],
  //   date: "1940",
  //   location: "Paris, France",
  //   description: "",
  //   metlink: "https://www.ahm.cn/En/Collection/Details/En_pylzp?nid=503"},
  // {
  //   key: 9,
  //   image: "/main-gallery/portrait9.jpg",
  //   imgAlt: "",
  //   imgCrop: "/main-gallery/portrait9.jpg",
  //   title: "Yellow Wings, A Cheyenne Woman",
  //   artist: "Joseph Henry Sharp",
  //   artistDesc: "Mexican painter Frida Kahlo was a revolutionary famous for her works depicting her struggles with her body image and gender identity. She is particularly well known for her self-portraits with her iconic unibrow, braided hair and traditional clothing. She spent most of her time as an artist in the United States and Mexico and later became an outspoken participant in the Mexican revolution in the 1910’s and 20s.",
  //   artistPic: "/main-gallery/frida-kahlo/frida-kahlo.jpg",
  //   other: [
  //     {otitle: "Memory, the Heart", oimg: "/main-gallery/frida-kahlo/fk-memory.jpg", odate: "1937"},
  //     {otitle: "What the Water Gave Me", oimg: "/main-gallery/frida-kahlo/fk-water.jpg", odate: "1938"},
  //     {otitle: "Self-Portrait with Monkey", oimg: "/main-gallery/frida-kahlo/sp-monkey.jpg", odate: "1938"},
  //   ],
  //   date: "1900",
  //   location: "",
  //   description: "",
  //   metlink: "https://americanart.si.edu/artwork/yellow-wings-22226"}
]

export default arr